eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: study-demo-api
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: studt-demo-client
    api-b:
      path: /api-b/**
      serviceId: study-demo-hystrix
